name: B2blue - TMDB CI by Rodrigo Delfino

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2


    # Setup Python (faster than using Python container)
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install pipenv
      run: |
        python3 -m pip install --upgrade pipenv wheel

    - name: Display Python version
      run: python3 --version

    - name: Install dependecies
      run: |
        pipenv install -d

    - name: Run tests with pipenv and pytest
      run: |
        pipenv run pytest

    - name: Code best pratices style
      run: |
        pipenv run flake8
